import { IconType } from "react-icons";

import {
  HiChevronUp,
  HiChevronDown,
  HiChevronRight,
  HiChevronLeft,
  HiArrowUpRight,
  HiOutlineArrowPath,
  HiCheck,
  HiMiniQuestionMarkCircle,
  HiMiniXMark,
  HiOutlineLink,
  HiExclamationTriangle,
  HiInformationCircle,
  HiExclamationCircle,
  HiCheckCircle,
  HiMiniGlobeAsiaAustralia,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiClipboard,
  HiArrowRight,
  HiClock,
  HiBolt,
  HiRocketLaunch,
  HiMagnifyingGlass,
  HiCog6Tooth,
  HiArrowTrendingUp,
  HiArrowPath,
  HiLightBulb,
  HiChartBar,
  HiPresentationChartLine,
  HiCursorArrowRays,
  HiSquares2X2,
  HiFlag,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaXTwitter,
  FaInstagram,
  FaThreads,
} from "react-icons/fa6";

import {
  SiNotion,
  SiFigma,
  SiPython,
  SiZapier,
  SiGooglesheets,
  SiGoogle,
  SiGoogleanalytics,
  SiTiktok,
  SiPosthog,
  SiMake,
  SiFacebook,
} from "react-icons/si";

export const iconLibrary: Record<string, IconType> = {
  chevronUp: HiChevronUp,
  chevronDown: HiChevronDown,
  chevronRight: HiChevronRight,
  chevronLeft: HiChevronLeft,
  refresh: HiOutlineArrowPath,
  arrowUpRight: HiArrowUpRight,
  check: HiCheck,
  arrowRight: HiArrowRight,
  helpCircle: HiMiniQuestionMarkCircle,
  infoCircle: HiInformationCircle,
  warningTriangle: HiExclamationTriangle,
  errorCircle: HiExclamationCircle,
  checkCircle: HiCheckCircle,
  email: HiEnvelope,
  globe: HiMiniGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  close: HiMiniXMark,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaXTwitter,
  instagram: FaInstagram,
  threads: FaThreads,
  clipboard: HiClipboard,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  external: HiArrowTopRightOnSquare,
  clock: HiClock,
  bulb: HiLightBulb,
  lightning: HiBolt,
  rocket: HiRocketLaunch,
  search: HiMagnifyingGlass,
  settings: HiCog6Tooth,
  repeat: HiArrowPath,
  target: HiFlag,
  chart: HiChartBar,
  "trending-up": HiArrowTrendingUp,
  analytics: SiGoogleanalytics,
  clarity: HiCursorArrowRays,
  amplitude: HiChartBar,
  whimsical: HiSquares2X2,
  // Brand / tool logos
  notion: SiNotion,
  figma: SiFigma,
  python: SiPython,
  zapier: SiZapier,
  sheets: SiGooglesheets,
  google: SiGoogle,
  tiktok: SiTiktok,
  posthog: SiPosthog,
  make: SiMake,
  facebook: SiFacebook,
};
